im:
  tcp:
    addr: ":8000"
  hosts:
    - {serverName: "server1",host: "127.0.0.1:8000",rpc: "127.0.0.1:18000"}
    - {serverName: "server2",host: "127.0.0.1:8001",rpc: "127.0.0.1:18001"}
    - {serverName: "server3",host: "127.0.0.1:8002",rpc: "127.0.0.1:18002"}

zap:
  logger:
    level: "debug"
    development: true
    disableCaller: false
    disableStacktrace: true
    sampling:
      initial: 100
      thereafter: 100
    encoding: "console"
    encoderConfig:
      messageKey: "msg"
      levelKey: "level"
      timeKey: "ts"
      nameKey: "logger"
      callerKey: "caller"
      functionKey: ""
      stacktraceKey: "stacktrace"
      lineEnding: "\n"
      levelEncoder: ""
      timeEncoder: "iso8601"
      durationEncoder: ""
      callerEncoder: "full"
      nameEncoder: ""
      consoleSeparator: ""
    outputPaths: ["stdout"]
    errorOutputPaths: ["stderr"]