// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: ids.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HandleId int32

const (
	HandleId_HI_None           HandleId = 0
	HandleId_HI_UserLoginQuery HandleId = 1
	HandleId_HI_MsgToUidQuery  HandleId = 2
	HandleId_HI_MsgToAllQuery  HandleId = 3
)

// Enum value maps for HandleId.
var (
	HandleId_name = map[int32]string{
		0: "HI_None",
		1: "HI_UserLoginQuery",
		2: "HI_MsgToUidQuery",
		3: "HI_MsgToAllQuery",
	}
	HandleId_value = map[string]int32{
		"HI_None":           0,
		"HI_UserLoginQuery": 1,
		"HI_MsgToUidQuery":  2,
		"HI_MsgToAllQuery":  3,
	}
)

func (x HandleId) Enum() *HandleId {
	p := new(HandleId)
	*p = x
	return p
}

func (x HandleId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HandleId) Descriptor() protoreflect.EnumDescriptor {
	return file_ids_proto_enumTypes[0].Descriptor()
}

func (HandleId) Type() protoreflect.EnumType {
	return &file_ids_proto_enumTypes[0]
}

func (x HandleId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HandleId.Descriptor instead.
func (HandleId) EnumDescriptor() ([]byte, []int) {
	return file_ids_proto_rawDescGZIP(), []int{0}
}

type HandleCode int32

const (
	HandleCode_HC_None                 HandleCode = 0
	HandleCode_HC_StatusOk             HandleCode = 200
	HandleCode_HC_StatusNotFound       HandleCode = 404
	HandleCode_HC_StatusServerInterval HandleCode = 500
)

// Enum value maps for HandleCode.
var (
	HandleCode_name = map[int32]string{
		0:   "HC_None",
		200: "HC_StatusOk",
		404: "HC_StatusNotFound",
		500: "HC_StatusServerInterval",
	}
	HandleCode_value = map[string]int32{
		"HC_None":                 0,
		"HC_StatusOk":             200,
		"HC_StatusNotFound":       404,
		"HC_StatusServerInterval": 500,
	}
)

func (x HandleCode) Enum() *HandleCode {
	p := new(HandleCode)
	*p = x
	return p
}

func (x HandleCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HandleCode) Descriptor() protoreflect.EnumDescriptor {
	return file_ids_proto_enumTypes[1].Descriptor()
}

func (HandleCode) Type() protoreflect.EnumType {
	return &file_ids_proto_enumTypes[1]
}

func (x HandleCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HandleCode.Descriptor instead.
func (HandleCode) EnumDescriptor() ([]byte, []int) {
	return file_ids_proto_rawDescGZIP(), []int{1}
}

type DataType int32

const (
	DataType_DT_Proto DataType = 0 //protobuf
	DataType_DT_Json  DataType = 1 //json
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0: "DT_Proto",
		1: "DT_Json",
	}
	DataType_value = map[string]int32{
		"DT_Proto": 0,
		"DT_Json":  1,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_ids_proto_enumTypes[2].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_ids_proto_enumTypes[2]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_ids_proto_rawDescGZIP(), []int{2}
}

var File_ids_proto protoreflect.FileDescriptor

var file_ids_proto_rawDesc = []byte{
	0x0a, 0x09, 0x69, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x5a, 0x0a, 0x08, 0x48,
	0x61, 0x6e, 0x64, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x0b, 0x0a, 0x07, 0x48, 0x49, 0x5f, 0x4e, 0x6f,
	0x6e, 0x65, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x48, 0x49, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x48,
	0x49, 0x5f, 0x4d, 0x73, 0x67, 0x54, 0x6f, 0x55, 0x69, 0x64, 0x51, 0x75, 0x65, 0x72, 0x79, 0x10,
	0x02, 0x12, 0x14, 0x0a, 0x10, 0x48, 0x49, 0x5f, 0x4d, 0x73, 0x67, 0x54, 0x6f, 0x41, 0x6c, 0x6c,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x10, 0x03, 0x2a, 0x61, 0x0a, 0x0a, 0x48, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x48, 0x43, 0x5f, 0x4e, 0x6f, 0x6e, 0x65,
	0x10, 0x00, 0x12, 0x10, 0x0a, 0x0b, 0x48, 0x43, 0x5f, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4f,
	0x6b, 0x10, 0xc8, 0x01, 0x12, 0x16, 0x0a, 0x11, 0x48, 0x43, 0x5f, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x10, 0x94, 0x03, 0x12, 0x1c, 0x0a, 0x17,
	0x48, 0x43, 0x5f, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x10, 0xf4, 0x03, 0x2a, 0x25, 0x0a, 0x08, 0x44, 0x61,
	0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x54, 0x5f, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x54, 0x5f, 0x4a, 0x73, 0x6f, 0x6e, 0x10,
	0x01, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_ids_proto_rawDescOnce sync.Once
	file_ids_proto_rawDescData = file_ids_proto_rawDesc
)

func file_ids_proto_rawDescGZIP() []byte {
	file_ids_proto_rawDescOnce.Do(func() {
		file_ids_proto_rawDescData = protoimpl.X.CompressGZIP(file_ids_proto_rawDescData)
	})
	return file_ids_proto_rawDescData
}

var file_ids_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_ids_proto_goTypes = []interface{}{
	(HandleId)(0),   // 0: HandleId
	(HandleCode)(0), // 1: HandleCode
	(DataType)(0),   // 2: DataType
}
var file_ids_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ids_proto_init() }
func file_ids_proto_init() {
	if File_ids_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ids_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ids_proto_goTypes,
		DependencyIndexes: file_ids_proto_depIdxs,
		EnumInfos:         file_ids_proto_enumTypes,
	}.Build()
	File_ids_proto = out.File
	file_ids_proto_rawDesc = nil
	file_ids_proto_goTypes = nil
	file_ids_proto_depIdxs = nil
}
